### ISSUE TITLE
Sonarr calendar and future episodes 

### ISSUE THREAD

**Issue by goku-son** [jeremysherriff/HTPC-Manager#14]
I was wondering if can take another look at this issue:

https://github.com/Hellowlol/HTPC-Manager/issues/601

I was hoping that perhaps a screenshot may illustrate the issue better than I can describe. Below is a screenshot for the Sonarr dashboard calendar:
![b8779573-68c2-4111-b546-460b627b9ed1](https://user-images.githubusercontent.com/20881936/46446205-99fb0780-c740-11e8-8744-93d8df322c48.jpeg)
Two of the above shows have yet to air and I would expect them to show up blue because they are not missed. Only after they air and get downloaded do they show up as green. Is this considered expected behavior? Thanks in advance.

**Comment by goku-son** [comment]
Here is how the calendar looks in Sonarr for reference:
![698ab308-8166-4f77-999e-ec7f66f8f1dd](https://user-images.githubusercontent.com/20881936/46446357-6cfb2480-c741-11e8-888d-4cb0cb4729cc.jpeg)

**Comment by jeremysherriff** [comment]
Wrong repository
