### ISSUE TITLE
Feedback thread: Ombi module

### ISSUE THREAD

**Issue by jeremysherriff** [jeremysherriff/HTPC-Manager#8]
Feedback and questions on the Ombi module.  If you have  an issue, start a new one so it can be referenced in commit, and closed when sorted.

👍 Thanks for participating!

**Comment by Kazz3r24** [comment]
Working well so far! Looking forward to being able to view TV requests as well ;)

**Comment by jeremysherriff** [comment]
Thanks @Kazz3r24 
Do you use HTPC via mobile? Or can you do some testing via mobile? I'm conscious that I have only tested via one device so different screen sizes/resolutions might not work so well.

**Comment by Kazz3r24** [comment]
Dropdowns all look good. I've added a couple screen caps of how it looks from a Pixel 2. That should encompass anything for that screen size at least. I'll keep documenting as I go along and take screen shots when I see something that doesn't look quite right.
Let me know if there's anything else I can do to assist!

![screenshot_20180827-192226](https://user-images.githubusercontent.com/15070472/44692035-19553700-aa2f-11e8-8f29-e88982400f6a.png)
![screenshot_20180827-192234](https://user-images.githubusercontent.com/15070472/44692096-66390d80-aa2f-11e8-913b-cd09d2719010.png)

**Comment by jeremysherriff** [comment]
Updated with fix for stale auth token. Have started looking at TV stuff but have never used Ombi for TV content so might take a bit to get my head around it.

Edit: Holy crap TV is handled a LOT differently to movie content.

**Comment by jeremysherriff** [comment]
@Kazz3r24 have you got a suggestion about how to lay out the Show/Series/Episode info for requested shows?

I was originally thinking I will need to expand on the Movies concept I've already done, of a line per requested show and then have a button to click that expands the row into a full-blown season/episode table showing the request status etc.  That table is likely to have it's own set of tabs for the seasons, and rows for the episodes.
The possible number of seasons and episodes is quite large, so the tabs will need to be small and the episode text reasonably small too - or at least the rows would need to be reasonably compact like Ombi itself does.  I season tabs would need to wrap for the mobile view too.  That all sounds hard.. lol

How about a click that navigates to a dedicated page layout for that show?  It would follow the current layout but instead of a tab for movie requests/movie searches/tv requests/etc it would be a tab per season instead.  Same potential issues for small screens with shows that have lots of seasons.

I guess I could also break it down further and do a whole page per season, with hyperlinks to the other seasons of the same show.

Thoughts?

**Comment by Kazz3r24** [comment]
Ahaha it kinda sounds like you answered your own question :P. I personally would go with the dedicated page for each show, allowing for a larger number of seasons etc to be displayed in rows. I'd have the general show title listing with your "processing, available, requested, etc" drop-down buttons like the movies are already displayed, then upon clicking on a show title, it'll move to a dedicated page that gives show details and the season and episode listings on that page. It'll give you a lot more room to work with on the screen, that way the fonts won't need to be so tiny. Especially when you have a show with a large number of seasons/episodes being requests, it won't be too hard on the eyes to look at. For a mobile view, I'd have the top row (wherever the seasons are listed) then run underneath itself, to allow for the larger number of seasons - without compromising the overall look of everything else. 
Example: 
1 2 3 4 5 6 7 8 9 10 11 12
13 14 15 16 17 18 19 20 21
Something like that. No matter what you do here someone is going to bitch about it looking ugly or something, but at the end of the day - it's the only way I can currently see to make it work. I get A LOT of reality TV show requests, which unfortunately most of them have been running for over a decade (or at least have 20 seasons with 50 episodes per)...I hate reality TV lol. Just thinking of a request like that coming in, I'd want the season table shown like the above, it's reasonably easy to navigate, and it doesn't need to be scrunched up too much.

Unless a user an admin is only approving a couple seasons of a show or a few episodes per season, they'll just be approving the whole show anyway, so the approve button would be on the main show listings page to approve it all at once.

Make sense? I can try to elaborate more if needed, but essentially I'm agreeing with your second possible option lol. Thinking of it now, it'll effectively be like looking at Sonarr or Sickrage. Sickrage has the seasons and episodes all layed out for you though, which inevitably results in a tonne of scrolling if it sorts from most recent to older, so having expandable seasons to list the episodes or something like that would be a good idea.

**Comment by jeremysherriff** [comment]
I've now got an actual TV request via Ombi so I can see what it loos like, they don't make tabs of the seasons they just it all under one another.  That might be a good starting point, and then see whether I can collapse it or make links to each season so it's easier to jump around.

There's benefits to keeping it all in one page, mostly because once you approve one thing you often want to approve another.

**Comment by jeremysherriff** [comment]
I've just pushed an update with a prototype Requests layout for TV shows.
It's a work in progress from the point of view that there are no actual 'approve' 'deny' etc buttons but the content is all there (seasons, requester info, season navigation quick-links).
Should work in mobile view too (tbh it's better on mobile lol).

Feedback is welcome, am open to suggestions on anything!

**Comment by jeremysherriff** [comment]
looool i have just discovered how bootstrap all works so i'm going to refactor all the visual elements to use it properly

I'll get the actual functions working and then do the refactoring - better to deliver something that works and is ugly, than take ages to deliver something prettier

edit: maybe not? it's looking pretty good and consistent with the theme components on every other HTPC page (like radarr)

**Comment by jeremysherriff** [comment]
New release pushed - all functions on the TV Requests page now work (approve/deny/remove/mark as un/available).
Minor stuff outstanding regarding episode status for requested stuff that is now available.
One bug: #9

**Comment by jeremysherriff** [comment]
YAY I finally got a TV request to work.
Needs some code clear-up and response handling but I'll be pushing a commit some time today that includes all working functionality for TV and Movies, both requesting and maintaining.

I need to back-port the (very clean-looking) "TV Search" page layout to fix the naff-looking "TV Requests" layout, hopefully squashing bug #9 at the time.  But I'll do that over the coming week as I'd rather get a functional version up, worry about prettiness later.

**Comment by jeremysherriff** [comment]
Pull Request submitted to main HTPC-Manager branch:
Hellowlol/HTPC-Manager#597
🔥 💪

**Comment by jeremysherriff** [comment]
![image](https://user-images.githubusercontent.com/1082213/45732894-77da9300-bc32-11e8-87e3-1a017cd0a02a.png)

**Comment by Kazz3r24** [comment]
It's looking awesome! I haven't run into any issues on my end so far, I will try to break it this weekend and see if I have any success.

**Comment by jeremysherriff** [comment]
Big visual clean-up and code refactor for TV Requests page, now uses the same logic as TV Search page.
Overlay contents is reflowed dynamically and actions are now reflected when buttons are clicked without page redraws.

**Comment by goku-son** [comment]
@jeremysherriff is this all already merged with the master2 branch? If not, is there any info on where to pull it down from and how to install it? Thanks in advance.

**Comment by jeremysherriff** [comment]
@goku-son no it isn't, I created a pull request but there are some problems with the code quality haha

You can pull it/install it by cloning this repository and switching to 'master3' branch, either over the top of the existing HTPC-Manager one or in a 2nd directory and changing which one runs by editing your startup/service script for HTPC-Manager.

ETA on it being included in the 'proper' repo is probably 3 weeks, maybe sooner if I can figure out how to code python better

**Comment by jeremysherriff** [comment]
Doing code clean-up to try and get the pull request to the main repo accepted. May have introduced bugs, if you find anything let me know.

**Comment by goku-son** [comment]
Update resolved the issue. I will monitor over the next few days to see if anything else appears broken. Thanks much!

**Comment by jeremysherriff** [comment]
Code clean-up for this has been completed, hopefully the pull request will now be accepted.
There might be a bug or two as I haven't fully tested every aspect of every function for the code clean-up. Holler if you find something.

**Comment by goku-son** [comment]
Did the PR for this get accepted yet?

**Comment by jeremysherriff** [comment]
Yep, is live and operational on the standard HTPC repo.

**Comment by goku-son** [comment]
Awesome had it all this time and did not even notice. A a few things I noted:

1. Test button fails although the log shows auth successful and I can see stuff in the module

2. Although there are pending requests when I add movies and tv requests to the dashboard only tv requests show items but movie requests say “No outstanding requests”

3. On the movie request the last column called “requestor”: this shows that I think is the date the movie was requested. Should the column not be named “date requested” or something similar?  It certainly would be nice to actual see the requestor (the user that made the request).

**Comment by jeremysherriff** [comment]
Can you post a screenshot of the movie request page, it should show both requester and requested date similar to the release date column, like this:
![image](https://user-images.githubusercontent.com/1082213/46579643-5f5fda80-ca72-11e8-86cc-a1756fe2b5af.png)

For the dash widget, it will only show things that are in the "Pending" state.  Again, screenshots will help if you believe this is not working.

**Comment by jeremysherriff** [comment]
The Movie Request page columns are part of a known bug that causes the table sorter to break, I think because it can't work out if it's numeric or text data to sort.

The main reason for wanting sort to work on request date is that I see that as being the most intuitive field to use as a default sort - your newest requests would be at the top and they are the ones that are most likely to need approving/reviewing.

I was thinking of dealing with it in one of two ways:
1. Remove the Release Status column and split the Requester column back into two distinct columns (the Requester person, and the requested date). Pros: Easy to do. Cons: We lose visibility (and sort ability) of the release info.  I could add the Release info to the (i) hover on the title but that obviously isn't sortable.
2. Make the Requester column just the person's name, and then have a hover (i) type thing for the date. Do same for the Release Status column. Pros: Easy to do. Cons: Can't sort by the dates.
3. Split both double-data columns' info out to make 6 columns total. Pros: Very easy to do. Cons: Mobile view now cramped, or mobile view will need to scroll left/right.

Feedback please, @goku-son @Kazz3r24 and others

**Comment by goku-son** [comment]
Movies are in either processing or available state:
![e486a6bb-45c2-4d29-a357-952d180b68d8](https://user-images.githubusercontent.com/20881936/46585192-3835e880-ca33-11e8-82f1-d0771b0790b7.jpeg)

I don’t show a requestor in the module:
![7c82ffd0-4938-4cda-8069-d28580685a2a](https://user-images.githubusercontent.com/20881936/46585201-6287a600-ca33-11e8-8ae0-42f47499fad0.jpeg)

**Comment by jeremysherriff** [comment]
Ok the dash widget is working as expected (nothing pending, so no actions required in any requests).

That Requester column is interesting. I'll get you to grab the output of a diag url, stand by for details.

**Comment by jeremysherriff** [comment]
Can you grab a screenshot the similar info of a request in Ombi's native console? I assume it displays the requester correctly there?

**Comment by jeremysherriff** [comment]
@goku-son can you grab the whole output from this test URL, copy/paste it into a text file and DM it to me (I assume we can attach files in a DM?).  It will be a giant wall of text.  Stick it in pastebin if you're not too worried about privacy stuff.

Assuming you're running behind a reverse proxy, the URL will be: http://serverip/htpc/ombi/movie_requests

Edit: If your HTPC install is externally accessible, you could also set me a up a user and send me the URL and credentials..?

**Comment by jeremysherriff** [comment]
@goku-son any updates on these topics?

**Comment by goku-son** [comment]
@jeremysherriff apologies as I got pulled elsewhere. 

Yes, the requestor does show up in native Ombi. If you need the screen grab I can get it. 

I am not behind a reverse proxy so let me know what url you need me to access given that. 

Also, on my previous post about the Ombi movies dashboard widget, I know you mentioned that only movies in pending status would show up. Requests for both movies and tv shows both auto-approve so my requests would only ever be in a processing or available status. I guess what is throwing me off is that you can see I got items showing up in Ombi TV Requests and those are not in a pending state. Is there a difference between the tv and movie dashboard widgets that determines what if anything gets displayed?

**Comment by jeremysherriff** [comment]
Hiya @goku-son, no problems!

I fixed a couple of little things but need more info on the others.  Test button now works properly, TV dash widget now displays "no requests", just little stuff.

Depending on how you run HTPC, you might need the :8085 (or whatever port you use) bit in if that's how you normally access the HTPC-Manager application.  It'll be a wall of text but it's the detail I need.  So the url might actually be http://serverip:8085/ombi/movie_requests instead.  Basically, get to the ombi page in HTPC, and add '/movie_requests' on the end of the /ombi bit 👍 

Do you use aliases (in Ombi) for your users?  I had a thought last night that I'm accessing the ".alias" attribute of the requester's name, which I thought was populated with the real name if no alias is defined.  But then talking to the guy who wrote Ombi, the same API is used for Ombi itself so the alias field is actually the real alias, I would need to check if the alias has something in it and then use the .name field if the alias is null 😄 

In answer to your question about the difference between the TV and Movie dash widgets, there's no intended difference.  In order to work out what is going on, you could grab me the output of two other urls: ombi/dashboard?t=movies and ombi/dashboard?t=tvlite
Those will give me the raw stuff, and I should be able to work out what's going on from there.

You might find that the dash widgets have no value for you; once things are in "processing" state then Ombi is hands off, and it's actually Radarr/Sonarr/Couch etc that offer useful info.  But have a think about it, and let me know if you think there is a useful criteria for the situation where the requests are approved - maybe I need to code up another pair of widgets that should things that are processing but not available?  Or a switch to flip between the two views?

Cheers for helping

**Comment by jeremysherriff** [comment]
Yes I've been able to replicate your issue by removing the alias from a user:
![image](https://user-images.githubusercontent.com/1082213/46777532-38ecb880-cd6c-11e8-8f06-008dd26787d8.png)
I'll code a fix this weekend and submit it

**Comment by jeremysherriff** [comment]
Was easy after all, so have patched already.
Pull request sent to the main repo with fixes for;
- Request owner not showing if user has no alias
- TV widget doesn't correctly display 'no pending requests' when empty
- Test button always indicates failure even though logs say successful

If you're on my repo then you'll already have these (or will do if you do an update).

Still waiting for info about TV widget showing more than just pending requests. Have also lodged request with Ombi as on the surface this appears to be an Ombi bug, or at least an inconsistency with the Ombi API responses.

**Comment by goku-son** [comment]
That is great news! If I did not want to wait for the merge how could I transfer to your branch? I only have master2 in the drop down. 

The info from the movies and tv dashboard widgets is below. I agree that the way I currently use it with auto approve would make these widgets useless to me at least. I will say I like the idea of instead displaying or at least have the option to display things that are processing. Sort of like the CP widget shows wanted movies. Good use case to get view of what’s been requested by your users. 

Movies dash:
{"total": 0, "collection": []}

TV shows dash (sanitized):
{"total": 0, "collection": [{"posterPath": "https://static.tvmaze.com/uploads/images/medium_portrait/156/390254.jpg", "status": "Running", "childRequests": [{"available": false, "canApprove": false, "issueId": null, "subscribed": false, "seasonRequests": null, "requestType": 0, "requestedDate": "2018-10-03T03:21:08.4419541", "id": 347162, "title": "The Fourth Estate", "markedAsDenied": "0001-01-01T00:00:00", "markedAsApproved": "0001-01-01T00:00:00", "approved": true, "markedAsAvailable": null, "deniedReason": null, "parentRequestId": 343274, "requestedUser": {"lockoutEnd": null, "movieRequestLimit": 0, "lastLoggedIn": "2018-10-09T00:54:26.297654", "userType": 1, "userAccessToken":999999999999999999999", "lockoutEnabled": true, "normalizedUserName": "user1", "id": "9bd74868-8bc2-4cea-9999-9999999", "userAlias": "user1", "normalizedEmail": "user1@GMAIL.COM", "episodeRequestLimit": 0, "embyConnectUserId": null, "twoFactorEnabled": false, "providerUserId": null, "phoneNumber": null, "accessFailedCount": 0, "email": "user1@gmail.com", "notificationUserIds": null, "phoneNumberConfirmed": false, "emailLogin": false, "isEmbyConnect": false, "userName": "user1", "alias": "", "emailConfirmed": false, "isSystemUser": false}, "denied": null, "showSubscribe": true, "requestedUserId": "9bd74868-8bc2-4cea-9999-99999999999", "seriesType": 0, "issues": null}], "qualityOverride": null, "tvDbId": 347162, "title": "The Fourth Estate", "imdbId": "tt8106552", "releaseDate": "2018-05-27T00:00:00", "background": "/qgUetqNcUNdSoBpAO19WLRyeO0c.jpg", "overview": "This documentary series about The New York Times in the Trump era illuminates critical issues facing journalism today. A chief task for the Times, long considered the \"newspaper of record,\" is to find the best way to accurately and honestly cover this unconventional president, even as he tries to undermine them. Through extraordinary access and exclusive interviews, Oscar\u00ae nominated filmmaker Liz Garbus chronicles the tenacious men and women in the trenches who are fighting for the freedom of the press and America's right to know.", "id": 343274, "rootFolder": null, "totalSeasons": 0}, {"posterPath": "https://static.tvmaze.com/uploads/images/medium_portrait/163/407569.jpg", "status": "Running", "childRequests": [{"available": true, "canApprove": false, "issueId": null, "subscribed": false, "seasonRequests": null, "requestType": 0, "requestedDate": "2018-09-21T03:28:07.4838317", "id": 329089, "title": "Ozark", "markedAsDenied": "0001-01-01T00:00:00", "markedAsApproved": "0001-01-01T00:00:00", "approved": true, "markedAsAvailable": "2018-09-22T04:30:10.0483894", "deniedReason": null, "parentRequestId": 343273, "requestedUser": {"lockoutEnd": null, "movieRequestLimit": 0, "lastLoggedIn": "2018-10-09T00:54:26.297654", "userType": 1, "userAccessToken": "9999999999999", "lockoutEnabled": true, "normalizedUserName": "user1", "id": "9bd74868-8bc2-4cea-9999-99999999999", "userAlias": "User1", "normalizedEmail": "user1@GMAIL.COM", "episodeRequestLimit": 0, "embyConnectUserId": null, "twoFactorEnabled": false, "providerUserId": null, "phoneNumber": null, "accessFailedCount": 0, "email": "user1@gmail.com", "notificationUserIds": null, "phoneNumberConfirmed": false, "emailLogin": false, "isEmbyConnect": false, "userName": "user1", "alias": "", "emailConfirmed": false, "isSystemUser": false}, "denied": null, "showSubscribe": true, "requestedUserId": "9bd74868-8bc2-4cea-9999-9999999999", "seriesType": 0, "issues": null}], "qualityOverride": null, "tvDbId": 329089, "title": "Ozark", "imdbId": "tt5071412", "releaseDate": "2017-07-21T00:00:00", "background": "/eLluMqJUIBRo0M5AP6ckLcSyeSb.jpg", "overview": "In this dark, dangerous series, a family struggles after moving to an Ozarks resort community when they're thrust into a world of dirty money.", "id": 343273, "rootFolder": null, "totalSeasons": 0}, {"posterPath": "https://static.tvmaze.com/uploads/images/medium_portrait/162/407241.jpg", "status": "Running", "childRequests": [{"available": false, "canApprove": false, "issueId": null, "subscribed": false, "seasonRequests": null, "requestType": 0, "requestedDate": "2018-09-10T10:37:11.4940191", "id": 336924, "title": "YOU", "markedAsDenied": "0001-01-01T00:00:00", "markedAsApproved": "0001-01-01T00:00:00", "approved": true, "markedAsAvailable": null, "deniedReason": null, "parentRequestId": 343272, "requestedUser": {"lockoutEnd": null, "movieRequestLimit": 0, "lastLoggedIn": "2018-09-13T22:25:17.465417", "userType": 1, "userAccessToken":999999999999999999999", "lockoutEnabled": true, "normalizedUserName":user2", "id": "ef4b5a75-99c6-426a-be22-d67cd5fdc87d", "userAlias": "user2", "normalizedEmail": "user2@GMAIL.COM", "episodeRequestLimit": 0, "embyConnectUserId": null, "twoFactorEnabled": false, "providerUserId": null, "phoneNumber": null, "accessFailedCount": 0, "email": "user2@gmail.com", "notificationUserIds": null, "phoneNumberConfirmed": false, "emailLogin": false, "isEmbyConnect": false, "userName": "user2", "alias": "", "emailConfirmed": false, "isSystemUser": false}, "denied": null, "showSubscribe": true, "requestedUserId": "ef4b5a75-99c6-426a-9999-9999999", "seriesType": 0, "issues": null}], "qualityOverride": null, "tvDbId": 336924, "title": "YOU", "imdbId": "tt7335184", "releaseDate": "2018-09-09T00:00:00", "background": "/sa7Ya0Rc1KgETjDSmdmfuZZO4kr.jpg", "overview": "Based on Caroline Kepnes' best-selling novel of the same name, YOU is a 21st century love story that asks, \"What would you do for love?\" When a brilliant bookstore manager crosses paths with an aspiring writer, his answer becomes clear: anything. Using the internet and social media as his tools to gather the most intimate of details and get close to her, a charming and awkward crush quickly becomes obsession as he quietly and strategically removes every obstacle - and person - in his way.", "id": 343272, "rootFolder": null, "totalSeasons": 0}, {"posterPath": "https://static.tvmaze.com/uploads/images/medium_portrait/163/409081.jpg", "status": "In Development", "childRequests": [{"available": false, "canApprove": false, "issueId": null, "subscribed": false, "seasonRequests": null, "requestType": 0, "requestedDate": "2018-09-08T15:27:10.5205073", "id": 348841, "title": "Kidding", "markedAsDenied": "0001-01-01T00:00:00", "markedAsApproved": "0001-01-01T00:00:00", "approved": true, "markedAsAvailable": null, "deniedReason": null, "parentRequestId": 343271, "requestedUser": {"lockoutEnd": null, "movieRequestLimit": 0, "lastLoggedIn": "2018-10-09T00:54:26.297654", "userType": 1, "userAccessToken":9999999999999999999", "lockoutEnabled": true, "normalizedUserName": "user1", "id": "9bd74868-8bc2-9999-89999999", "userAlias": "user1", "normalizedEmail": "user1@GMAIL.COM", "episodeRequestLimit": 0, "embyConnectUserId": null, "twoFactorEnabled": false, "providerUserId": null, "phoneNumber": null, "accessFailedCount": 0, "email": "user1@gmail.com", "notificationUserIds": null, "phoneNumberConfirmed": false, "emailLogin": false, "isEmbyConnect": false, "userName": "user1", "alias": "", "emailConfirmed": false, "isSystemUser": false}, "denied": null, "showSubscribe": true, "requestedUserId": "9bd74868-8bc2-4cea-9999-9999999999", "seriesType": 0, "issues": null}], "qualityOverride": null, "tvDbId": 348841, "title": "Kidding", "imdbId": "tt7375404", "releaseDate": "2018-09-09T00:00:00", "background": "/fV09mT0VMBmwElsFowSC0qoPyD3.jpg", "overview": "Kidding follows Jeff, aka Mr. Pickles, an icon of children's television, a beacon of kindness and wisdom to America's impressionable young minds and the parents who grew up with him \u2013 who also anchors a multimillion-dollar branding empire.But when this beloved personality's family \u2013 wife, two sons, sister and father \u2013 begins to implode, Jeff finds no fairy tale or fable or puppet will guide him through the crisis, which advances faster than his means to cope. The result: a kind man in a cruel world faces a slow leak of sanity as hilarious as it is heartbreaking.", "id": 343271, "rootFolder": null, "totalSeasons": 0}, {"posterPath": "https://static.tvmaze.com/uploads/images/medium_portrait/138/346474.jpg", "status": "Ended", "childRequests": [{"available": true, "canApprove": false, "issueId": null, "subscribed": false, "seasonRequests": null, "requestType": 0, "requestedDate": "2018-09-02T22:19:58.7580186", "id": 334153, "title": "Wormwood", "markedAsDenied": "0001-01-01T00:00:00", "markedAsApproved": "0001-01-01T00:00:00", "approved": true, "markedAsAvailable": null, "deniedReason": null, "parentRequestId": 343270, "requestedUser": {"lockoutEnd": null, "movieRequestLimit": 0, "lastLoggedIn": "2018-10-09T00:54:26.297654", "userType": 1, "userAccessToken": "3a10bbe271414f4899999999999", "lockoutEnabled": true, "normalizedUserName": "user1", "id": "9bd74868-8bc2-4cea-9999-99999999999", "userAlias": "users 1", "normalizedEmail": "user1@GMAIL.COM", "episodeRequestLimit": 0, "embyConnectUserId": null, "twoFactorEnabled": false, "providerUserId": null, "phoneNumber": null, "accessFailedCount": 0, "email": "user1@gmail.com", "notificationUserIds": null, "phoneNumberConfirmed": false, "emailLogin": false, "isEmbyConnect": false, "userName": "user1", "alias": "", "emailConfirmed": false, "isSystemUser": false}, "denied": null, "showSubscribe": true, "requestedUserId": "9bd74868-8bc2-4cea-9999-99999999", "seriesType": 0, "issues": null}], "qualityOverride": null, "tvDbId": 334153, "title": "Wormwood", "imdbId": "tt7306056", "releaseDate": "2017-12-15T00:00:00", "background": "/gjWWC5LcCF8julFLE1EtmZUzYd0.jpg", "overview": "In this genre-bending tale, Errol Morris explores the mysterious death of a U.S. scientist entangled in a secret Cold War program known as MK-Ultra.", "id": 343270, "rootFolder": null, "totalSeasons": 0}]}

**Comment by jeremysherriff** [comment]
Thanks @goku-son 
Picking the relevant bits out and reformatting for readability:
````
{
  "title": "The Fourth Estate",
    [{
		"available": false,
		"approved": true,
		"denied": null,
    }],
},
{
  "title": "Ozark",
    [{
		"available": true,
		"approved": true,
		"denied": null,
    }],
},
{
  "title": "YOU",
    [{
		"available": false,
		"approved": true,
		"denied": null,
    }],
},
{
  "title": "Kidding",
    [{
		"available": false,
		"approved": true,
		"denied": null,
    }],
},
{
  "title": "Wormwood",
    [{
		"available": true,
		"approved": true,
		"denied": null,
    }],
}
````

So these are all approved (you auto-approve so that is right) and you have a mixture of both `processing` and `available` states. Nothing has been `denied`.

I have confirmation back from the guy that writes Ombi itself that the TV filtering is a work in progress.  That's why in Ombi's native interface you see no blue filter button on the TV Requests screen, but you do on both the Movies and Music Requests screens.

At this point I'm going to have to say that as this is not implemented fully in Ombi, it's outside my ability to fix.

**Comment by jeremysherriff** [comment]
@goku-son to switch to this repo instead of Hellowlol's proper one, you simply download from the Code page on my Git 
![image](https://user-images.githubusercontent.com/1082213/46847895-445ee300-ce43-11e8-8c58-db86b07bdc7b.png)
and unpack the zip into a different folder than the HTPC install you already have.
Then simply copy the HTPC database from your current install into the same place in this new one.

It runs with exactly the same parameters, the databases are completely interchangeable, so you can copy the DB back to the other install at any time.

Use my `master2` branch the same as you do on the original repo - `master3` is my dev system and isn't guaranteed to be working.  However I might get you to switch to master3 to test something if we need to.

**Comment by goku-son** [comment]
Thanks for the update on the ombi widgets. Any chance that those could be repurposed to perhaps show processing states for movies and tv shows. In my use case, I would find that useful. Sort of like the CP wanted movies widget.

**Comment by jeremysherriff** [comment]
This module is intended to add functionality, not duplicate existing stuff.
Can you explain how your suggestion is better than simply using the respective (and existing) CP, Radarr, or Sonarr widgets?

**Comment by goku-son** [comment]
I guess I was thinking like Sonarr and CP it would be nice to have dashboard widgets for Ombi that at a galance shows you what is processing. Maybe showing 5 for each and if you want/need more detail you can go into the Ombi module itself. I guess I am thinking that the dash should give me high level info on all my important modules without having to go into the module itself unless I need more detail. If it requires too much effort and you think it is reproducing existing functionality then I am okay with using it as is just going into the module.

**Comment by jeremysherriff** [comment]
The thing is, Ombi is not involved at all once something is 'Processing'. Ombi literally has no part to play, and simply keeps checking Plex/Emby on a schedule to see if the content ever gets downloaded in order to update the state.

**Comment by goku-son** [comment]
understand I now see that it would not make sense to list Ombi processing requests thanks for explaining that part to me.

**Comment by jeremysherriff** [comment]
Fixes merged into main repo

**Comment by jeremysherriff** [comment]
All issues should now be raised in https://github.com/Hellowlol/HTPC-Manager/issues as per normal issues with HTPC.
